Handle Invalid scale and arcDegreeScale values in segments to avoid crash
shipt/segmented-arc-for-react-native pull request #114
Opened 2024-12-25 23:35 UTC by roni-castro-shipt

## Description 
Currently, when an invalid number (NaN) is passed as `arcDegreeScale`, Android crashes, and iOS generates an inconsistent graph.

## Solution:
- If the `arcDegreeScale` or `scale` is a finite number, parse it as usual. However, if either value is invalid (i.e., NaN, Infinity, or -Infinity, or any unexpected numeric value), issue a warning to the user and override the value with a default scale. This default will be calculated based on the remaining value needed to sum to 1 (current solution already). This ensures that neither `arcDegreeScale` nor `scale` will ever be NaN, preventing crashes.

- Issue a warning every time a SegmentArc is rendered for the first time, under the following conditions:
  1. Either `arcDegreeScale` or `scale` is not a finite number (i.e., NaN, Infinity, or -Infinity).
  2. A segment’s `arcDegreeScale` or `scale` value is outside the valid range of 0 (0%) to 1 (100%).
  3. The sum of all segment `scale` or `arcDegreeScale` values exceeds 1 or is less than 0.

Obs:
- In the current solution:
  - A `scale` value of zero is considered invalid, so it is overridden by `_ensureDefaultSegmentScale`. This behavior has been preserved.
  - A `arcDegreeScale` value of zero is considered valid, so it is not overridden by `_ensureDefaultArcScale`. This logic remains unchanged.
  - `scale` or `arcDegreeScale` values set to `undefined` are currently accepted as valid props. The previous functions `_ensureDefaultSegmentScale` and `_ensureDefaultArcScale` handle these values by evenly distributing the value across segments, so no warning is generated for these cases.

## Screenshots

### Android

| Before                                           | After                            |
| ------------------------------------------------ | -------------------------------- |
| <video src="https://github.com/user-attachments/assets/1550bf67-55e3-418b-be9e-37374721f308">  | <video src="https://github.com/user-attachments/assets/a7cf1f8e-a6d1-45c3-8ccf-d8d71037d40d"> |

### iOS

| Before                                           | After                            |
| ------------------------------------------------ | -------------------------------- |
| <video src="https://github.com/user-attachments/assets/e8ad5abb-389a-425c-89f5-4326ab7c77ab">  | <video src="https://github.com/user-attachments/assets/63bb202c-2df3-45b3-8592-fbd08388d998"> |

## Some possible warnings 

### arcDegreeScale

<img src="https://github.com/user-attachments/assets/269e1bcf-c08c-4a63-8b13-ebaaf852960a" alt="arcDegreeScale-10" >
<img src="https://github.com/user-attachments/assets/bb7a95fe-73eb-48e1-b68b-9aebb335c403" alt="arcDegreeScale+10" >
<img src="https://github.com/user-attachments/assets/735a0286-7424-4ca3-80cc-7857893e6b32" alt="arcDegreeScale_NaN" >
<img src="https://github.com/user-attachments/assets/e3fa1792-4d0f-4d57-bca1-374cbe3dc3ee" alt="arcDegreeScale_null" >

### scale

<img src="https://github.com/user-attachments/assets/4184dc09-83fc-4511-a469-47b3cbd5bc43" alt="scale_more_than_1">
<img src="https://github.com/user-attachments/assets/db449121-2795-4991-bdc4-a21fb4e7c45c" alt="scale_allocated_smaller_than_0" >
<img src="https://github.com/user-attachments/assets/ccb210dd-672c-426f-8fff-61f7d488b082" alt="scale_NaN" >

2025-01-03 02:23 UTC, jkhusanov reviewed
While I'll pull up and run the example app locally, couple of comments.

2025-01-03 21:57 UTC, roni-castro-shipt commented on src/utils/__tests__/scale.spec.js
> +    expect(segmentsResult).toEqual([{ arcDegreeScale: 1 / 2 }, { arcDegreeScale: 1 / 2 }]);
No. it's 1/2 because there're two segments in here `const segments = [{ arcDegreeScale: NaN }, { arcDegreeScale: NaN }];` so the default value would be 1 / numberOfSegments. I'll  `1 / segments.length ` to make it clear

2025-01-03 21:57 UTC, roni-castro-shipt commented on src/utils/warningManager.js
> +    warnings.add(key);
Yes, if I don't have that, it would show a warning on every state change, With set and this logic, it would show only when rendering the component for the first time

2025-01-03 22:07 UTC, jkhusanov commented on src/utils/__tests__/scale.spec.js
> +    expect(segmentsResult).toEqual([{ arcDegreeScale: 1 / 2 }, { arcDegreeScale: 1 / 2 }]);
I wanted to say could we do 0.5 ?

2025-01-03 22:20 UTC, roni-castro-shipt commented on src/utils/warningManager.js
> +    warnings.add(key);
This was to avoid depending on the `useShowSegmentedArcWarnings` useRef to just show the same warning once in case rerender happens, like when an array is passed directly as props without memoization, and avoid spamming multiple warnings per render. But I'll check if that is still needed

```js
<SegmentedArc segments={[ {scale: NaN} ]} />
```

2025-01-07 00:34 UTC, jkhusanov commented
I just noticed that if we have 3 segments with only one having a scale of 1 it crashes. Not blocking, I think.

```js
    {
      filledColor: '#FF746E',
      emptyColor: '#F2F3F5',
      data: { label: 'Red' },
    },
    {
      scale: 1,
      filledColor: '#F5E478',
      emptyColor: '#F2F3F5',
      data: { label: 'Yellow' },
    },
    {
      filledColor: '#78F5CA',
      emptyColor: '#F2F3F5',
      data: { label: 'Green' },
    },
```

2025-01-07 01:11 UTC, roni-castro-shipt commented
> I just noticed that if we have 3 segments with only one having a scale of 1 it crashes. Not blocking, I think.
> 
> ```js
>     {
>       filledColor: '#FF746E',
>       emptyColor: '#F2F3F5',
>       data: { label: 'Red' },
>     },
>     {
>       scale: 1,
>       filledColor: '#F5E478',
>       emptyColor: '#F2F3F5',
>       data: { label: 'Yellow' },
>     },
>     {
>       filledColor: '#78F5CA',
>       emptyColor: '#F2F3F5',
>       data: { label: 'Green' },
>     },
> ```

Great catch! The values are converting correctly adding a unit test with the values you shared, but it seems some flow still is generating a NaN. I'll debug to check.
```js
it('ensures default values for `scale` and `arcDegreeScale` are set', () => {
    expect(
      ensureDefaultSegmentScaleValues([
        {
          filledColor: '#FF746E',
          emptyColor: '#F2F3F5',
          data: { label: 'Red' }
        },
        {
          scale: 1,
          filledColor: '#F5E478',
          emptyColor: '#F2F3F5',
          data: { label: 'Yellow' }
        },
        {
          filledColor: '#78F5CA',
          emptyColor: '#F2F3F5',
          data: { label: 'Green' }
        }
      ])
    ).toEqual([
      {
        arcDegreeScale: 0.3333333333333333,
        scale: 0,
        filledColor: '#FF746E',
        emptyColor: '#F2F3F5',
        data: { label: 'Red' }
      },
      {
        arcDegreeScale: 0.3333333333333333,
        scale: 1,
        filledColor: '#F5E478',
        emptyColor: '#F2F3F5',
        data: { label: 'Yellow' }
      },
      {
        arcDegreeScale: 0.3333333333333333,
        scale: 0,
        filledColor: '#78F5CA',
        emptyColor: '#F2F3F5',
        data: { label: 'Green' }
      }
    ]);
  });
```

2025-01-07 01:26 UTC, roni-castro-shipt commented
> > I just noticed that if we have 3 segments with only one having a scale of 1 it crashes. Not blocking, I think.
> > ```js
> >     {
> >       filledColor: '#FF746E',
> >       emptyColor: '#F2F3F5',
> >       data: { label: 'Red' },
> >     },
> >     {
> >       scale: 1,
> >       filledColor: '#F5E478',
> >       emptyColor: '#F2F3F5',
> >       data: { label: 'Yellow' },
> >     },
> >     {
> >       filledColor: '#78F5CA',
> >       emptyColor: '#F2F3F5',
> >       data: { label: 'Green' },
> >     },
> > ```
> 
> Great catch! The values are converting correctly adding a unit test with the values you shared, but it seems some flow still is generating a NaN. I'll debug to check.
> 
> ```js
> it('ensures default values for `scale` and `arcDegreeScale` are set', () => {
>     expect(
>       ensureDefaultSegmentScaleValues([
>         {
>           filledColor: '#FF746E',
>           emptyColor: '#F2F3F5',
>           data: { label: 'Red' }
>         },
>         {
>           scale: 1,
>           filledColor: '#F5E478',
>           emptyColor: '#F2F3F5',
>           data: { label: 'Yellow' }
>         },
>         {
>           filledColor: '#78F5CA',
>           emptyColor: '#F2F3F5',
>           data: { label: 'Green' }
>         }
>       ])
>     ).toEqual([
>       {
>         arcDegreeScale: 0.3333333333333333,
>         scale: 0,
>         filledColor: '#FF746E',
>         emptyColor: '#F2F3F5',
>         data: { label: 'Red' }
>       },
>       {
>         arcDegreeScale: 0.3333333333333333,
>         scale: 1,
>         filledColor: '#F5E478',
>         emptyColor: '#F2F3F5',
>         data: { label: 'Yellow' }
>       },
>       {
>         arcDegreeScale: 0.3333333333333333,
>         scale: 0,
>         filledColor: '#78F5CA',
>         emptyColor: '#F2F3F5',
>         data: { label: 'Green' }
>       }
>     ]);
>   });
> ```


It's a division / zero in [here](https://github.com/shipt/segmented-arc-for-react-native/blob/73f62816dbccc17fa4edf7797db168a54b1500b2/src/SegmentedArc.js#L102)
![Screenshot 2025-01-06 at 22 21 39](https://github.com/user-attachments/assets/38826969-e150-4629-aeb7-8fa0e084d1ea)
I'll fix that soon
![Screenshot 2025-01-06 at 22 25 36](https://github.com/user-attachments/assets/130d6d79-7b8b-44a5-95fd-1786575f01a1)

2025-01-07 22:08 UTC, jkhusanov commented
@roni-castro-shipt

> I'll fix that soon

Let's not increase this PR's size, as it is already big enough and could have been split up. Let's aim to introduce one fix/feature per PR.

2025-01-07 23:24 UTC, roni-castro-shipt commented on src/utils/warningManager.js
> +    warnings.add(key);
If I remove the `warnings` set, the following will occur:

* The number of warnings displayed in the Metro Bundler will correspond to the number of invalid segments. For example, if there is 1 invalid segment, 1 log will appear; if there are 4 invalid segments, the console will display 4 warnings.
* LogBox, however, consolidates duplicate warnings and will display only a single warning, no matter the solution. Internally, LogBox likely suppresses logs with identical messages.

| Before      | After      |
|---------------|---------------|
| ![Screenshot 2025-01-07 at 20 14 30](https://github.com/user-attachments/assets/d0f1e122-18bf-4087-97db-17569c1f016a) |  ![Screenshot 2025-01-07 at 20 06 18](https://github.com/user-attachments/assets/c439f4cb-81d7-4842-9ac1-120d6eae56e6) |

Should I remove the `showWarningOnce` and allow multiple console.warn to appear on the metro terminal?
I mean change from this
```js
const warnings = new Set();

const showWarningOnce = (data, warnId = '') => {
  const message = data instanceof Error ? data.message : String(data);
  const key = message + warnId;

  if (!warnings.has(key)) {
    console.warn(data);
    warnings.add(key);
  }
};
```

to this, and update where necessary

```js
const showWarning = data => {
  console.warn(data);
};
```

2025-01-08 01:06 UTC, jkhusanov commented on src/utils/warningManager.js
> +    warnings.add(key);
If we don't show the same warning when something changes in the props or state, I think we can simplify this. Having more warnings in the metro bundler might be helpful even if the logbox suppresses it. Like, if a developer fixes one warning it will still show the warnings for the remainder and the developer would be less confused.

2025-01-08 01:07 UTC, jkhusanov commented on src/utils/warningManager.js
> +    warnings.add(key);
I'd like you to make a final decision on this. I don't want to discard your original concerns especially if you observed them happening.

2025-01-08 16:30 UTC, roni-castro-shipt commented on src/utils/warningManager.js
> +    warnings.add(key);
In this PR, `showWarningOnce` isn't needed due to useRef, which prevents useEffect from triggering on prop changes. Replacing it with `showWarning` is fine, as it's unlikely to cause many console.warn calls, considering the user probably doesn't have segments with 100+ NaN invalid scales. In the other draft PR, I'll need `showWarningOnce` because I'm using `WarningManager.showWarningOnce` directly and can't use a hook there.

```js
export const useShowSegmentedArcWarnings = ({ segments }) => {
  // Conditionally render hook, because this is not useful in production
  if (!__DEV__) return;

  const { current: currentSegments } = useRef(segments);
  const id = useId();

  useEffect(() => {
    //This is called just once because currentSegments is a ref
    warnAboutInvalidSegmentsData(currentSegments, id);
  }, [currentSegments]);
};
```

So, for this PR, I'll remove `showWarningOnce` and `clearAllWarnings`. In the other [one](https://github.com/shipt/segmented-arc-for-react-native/pull/115), add it back with some changes and use just where it is necessary.

2025-01-08 18:46 UTC, roni-castro-shipt commented on src/utils/warningManager.js
> +    warnings.add(key);
Done. The result will be like this now in this PR.
* show a warning in metro bundler per invalid segment.
* show a single warning in Logbox if they are identical (handled internally by the module)
* do not warnings again on rerender of the parent or the component itself
* show all warnings again on unmount/mount

https://github.com/user-attachments/assets/bbd0f2c4-8b8f-480c-b409-8f481543f358

2025-01-10 18:15 UTC, jkhusanov commented on src/__tests__/SegmentedArc.spec.js
> +    const newProperties = { ...props, segments: [{ ...props.segments[0], scale: NaN }] };
I think it's the same prop, not a new one.

2025-01-10 18:58 UTC, roni-castro-shipt commented on src/__tests__/SegmentedArc.spec.js
> +    const newProperties = { ...props, segments: [{ ...props.segments[0], scale: NaN }] };
It's a different reference of `segments`, so in a React context, it's new props, but if you prefer, can any to something like `{ ...props, segments: [{ ...props.segments[0], scale: NaN, scale: 0.5 }] };` to make it clearer.

2025-01-13 21:12 UTC, jkhusanov commented
Just discussed this in person, and agreed to these: 

1. When `scale` or `arcDegreeScale` is invalid, we would render a friendly message in the simple `<Text>` to the user instead of rendering the arc. That error message should be a prop that the developers can override.  
2. Add a new prop that receives a callback function that triggers when these errors occur. So developers can add error tracking on their end for those errors if they are returned from the component.

Keep the warnings that run in dev mode.

2025-01-15 19:54 UTC, roni-castro-shipt commented
> Just discussed this in person, and agreed to these:
> 
> 1. Add a message below the arc that says "Some issue with the arc data", and add a prop to override that message.
> 2. Add a new prop that receives a callback function that triggers when these errors occur. So developers can add error tracking on their end for those errors if they are returned from the component.
> 
> Keep the warnings that run in dev mode.
> 
> UPD: new requirements after group meeting.

For the item 1. Considering the user's app can allow dark mode or any background color for the parent view. We talked and decided to create a  `dataErrorComponent` prop, instead of `dataErrorMessage`

### Reason for `dataErrorComponent`

1. **Context**:  
   Since the user’s app may allow dark mode or have custom background colors, the error component may not be shown, so this prop will be created to give users control over error handling instead of relying on the library. 

2. **Default Settings**:  
   - **Background**: White  
   - **Text Color**: Black  
   These default styles ensure the error message is always visible, regardless of the app’s theme or background color.

3. **Customization**:  
   - Users can pass `null` to disable the error message entirely.  
   - Users can pass a **custom `dataErrorComponent`** to control how the error is displayed, adapting to dark mode or any specific design needs.

### Example

1. **Error Messages in Dark Mode**:  
   Default white background with black text.  
<img src="https://github.com/user-attachments/assets/f2b936ae-a532-4894-bdfc-e8579c6e3cab" width="350" />

2. **Error Messages with Custom Black Background**:  
   User-defined component with a black background, without passing `dataErrorComponent`.  
<img src="https://github.com/user-attachments/assets/60e6fb7a-13d9-4eb5-9bd7-8f554b58ed33" width="350" />

   User-overriding it to whatever he wants, passing custom `dataErrorComponent`
<img src="https://github.com/user-attachments/assets/23e465e6-89b6-4f32-b2ae-c6d426088b32" width="350" />


3. **Error Messages with light mode and no custom props**:  
<img src="https://github.com/user-attachments/assets/19a529f5-0464-4de6-8cac-cada49fd5733" width="350" />

2025-01-18 00:07 UTC, roni-castro-shipt reviewed
@jkhusanov All requested changes have been applied. However, there’s still a pending decision regarding how the `onDataError` callback is triggered: should it be called only once or multiple times? The issue arises because errors are regenerated every time the segments array changes (whether by reference or value). If the library's client does not memoize the callback, it may lead to the onDataError being called multiple times, particularly when the parent state changes.


Example:

https://github.com/user-attachments/assets/b88fe128-acf5-4485-aa5e-201297e390c3

Observation: RN Logbox uses JSON.stringify internally, which convert any `Infinity` or `NaN` to `null` values. But in the logs it's shown correctly. If the client need to use JSON.stringify to send to errors to the monitoring tool, it will generate invalid debug values, anyway.

![Screenshot 2025-01-17 at 21 05 22](https://github.com/user-attachments/assets/dc377774-ebfb-4157-a713-3ab7abdaf650)

2025-01-22 00:48 UTC, jkhusanov commented on README.md
> +| dataErrorComponent          | functional component, element or null                                                                     | DataError        | This prop allows you to override the com
I think we should include a link to `DataError` component and mention it's on by default. 
```suggestion
| dataErrorComponent          | functional component, element or null                                                                     | [DataError](./src/components/DataError.js)         | This prop allows you to override the component shown below the graph when invalid props are passed (e.g., scale = NaN or scale = 0). By default, it displays an error message to inform users that the data may be inaccurate. The library internally adjusts invalid values (e.g., changing NaN to a valid number) to prevent crashes. To hide this error, pass null instead. |
```

2025-01-22 00:48 UTC, jkhusanov commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
I was wondering something...  Any reasons why this simplified implementation would not be sufficient? 

```suggestion
  useEffect(() => {
    if (Object.keys(invalidSegments).length > 0 && callback) {
      callback(invalidSegments);
    }
  }, [invalidSegments]);

```

2025-01-22 00:50 UTC, jkhusanov commented
> @jkhusanov All requested changes have been applied. However, there’s still a pending decision regarding how the `onDataError` callback is triggered: should it be called only once or multiple times? The issue arises because errors are regenerated every time the segments array changes (whether by reference or value). If the library's client does not memoize the `segments` array, it may lead to the onDataError being called multiple times, particularly when the parent state changes.

I think this is fine, as it is how react works in general. The users of this package can apply optimizations on their end if they want to.

2025-01-22 00:53 UTC, jkhusanov commented on src/components/DataError.js
> +// Disabled because if the user wants to override it, he can pass dataErrorComponent with any customization
```suggestion
// Disabled because if a user wants to override it, they can pass dataErrorComponent with any customization
```

2025-01-22 00:56 UTC, roni-castro-shipt commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
1. The `callback` instance being used is the first one, not the latest, because it's not included in the useEffect dependency array. Including it in the dependencies would cause multiple warnings, especially if the callback is defined as anonymous, such as `onDataError={() => {...}}`.
2. While I could create a separate hook to calculate the errors, the current solution returns a dataError, which I then use to conditionally display the error component below the arc.
3. It can have more than one error in this lib, not only segments, so it would need to be at least pass `callback({segments: invalidSegments});`

2025-01-22 01:48 UTC, jkhusanov commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
Do you mean callback function can be dynamic that's why we want to watch it? I can't think of instances of it being changed after the component changes. We don't need to watch it in the array either.

2025-01-22 23:56 UTC, roni-castro-shipt commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
Considering the `callback` is used only when `invalidSegments` props are updated, I believe there'll be no bug removing the useRef besides breaking the react rule. So, I'll update this, as I said, I need the `dataError` object to defined If I can show/hide the `dataErrorComponent`

//useDataErrorHandler.js
```js
import { useEffect } from 'react';

const useDataErrorHandler = (callback, dataError) => {
  useEffect(() => {
    if (callback && Object.keys(dataError).length > 0) {
      callback(dataError);
    }
  }, [dataError]);
};

export default useDataErrorHandler;


```

// useDataError.js
```js
import { useEffect, useState } from 'react';

const useDataError = ({ invalidSegments }) => {
  const [dataError, setDataError] = useState({});

  useEffect(() => {
    setDataError(prevErrors => {
      const { ...errorsWithoutSegments } = prevErrors;
      delete errorsWithoutSegments.segments;
      return invalidSegments.length ? { ...errorsWithoutSegments, segments: invalidSegments } : errorsWithoutSegments;
    });
  }, [invalidSegments]);

  return dataError;
};

export default useDataError;

```

2025-01-23 00:03 UTC, jkhusanov commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
Why do you need useDataError if you can directly use `invalidSegments`?

2025-01-23 00:28 UTC, roni-castro-shipt commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
If I don't have a centralized place to detect data errors, I need to have the same business logic `invalidSegments.length > 0` in different places.

```js
import { useEffect } from 'react';

const useDataErrorCallback = (callback, {invalidSegments}) => {
  useEffect(() => {
    if (callback && invalidSegments.length > 0) {
      callback({segments: invalidSegments});
    }
  }, [dataError]);};

export default useDataErrorCallback;
```

and


 ```js
const hasInvalidProps =invalidSegments.length > 0
```

Now, let’s say I need to handle invalid props for `fillValue` and `arcDegree` in the next PR, as they are also causing crashes. The issue is that I would need to duplicate the error-handling logic in two separate places. If someone adds new error handling to the `useDataErrorCallback` but forgets to include it in the `const hasInvalidProps =invalidSegments.length > 0`, it could introduce a new bug.

2025-01-23 00:30 UTC, roni-castro-shipt commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
That's another alternative,  create a function like this to avoid needing another hook. 

Some utils
```js
export const getErrors = ({ invalidSegments }) => {
  let dataError = {};
  if (invalidSegments.length > 0) {
    dataError.segments = invalidSegments;
  }

  return dataError;
};
```

SegmentArc
```js
  const dataError = useMemo(() => getErrors({ invalidSegments }), [invalidSegments]);
  useDataErrorCallback(onDataError, dataError);
```
The difference is that it would need a useMemo, to not activate the `useDataErrorCallback` useEffect multiple times because of internal lib state change:
useDataErrorCallback
```js
import { useEffect } from 'react';

const useDataErrorCallback = (callback, dataError) => {
  useEffect(() => {
    if (callback && Object.keys(dataError).length > 0) {
      callback(dataError);
    }
  }, [dataError]);
};

export default useDataErrorCallback;
```

2025-01-23 19:58 UTC, jkhusanov commented on src/hooks/useDataErrorHandler.js
> +  }, [dataError]);
I think we can keep the original solution. It is best to follow React's practices to avoid additional questions or proposals to change it.

2025-01-23 20:05 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  }
Do you mean users could pass a function that returns type, props, and children?

2025-01-23 20:28 UTC, jkhusanov commented on src/utils/scale.js
can we rename this file to something like `scaleHelpers` or a better name so it doesn't sound like a component?

2025-01-23 20:52 UTC, roni-castro-shipt commented on src/components/DataErrorRenderer.js
> +  }
I mean a function component:
```js
const DataErrorComponent = () => <Text>Test Functional Component</Text>

dataErrorComponent={DataErrorComponent}
```

2025-01-23 22:51 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  }
I don't know if we should expect users to do this, if they do React should complain that they cannot pass functions like that. 

This is more common I think. 
```js
const DataErrorComponent =  ( 
   <Text>Test Functional Component</Text>  
) 
```

2025-01-24 01:14 UTC, jkhusanov commented on src/utils/scaleHelpers.js
> +      (segment.scale !== undefined && _isInvalidScale(segment.scale)) ||
should we also check for `scale < 0 || scale >1` like in the warnings: 

https://github.com/shipt/segmented-arc-for-react-native/pull/114/files#diff-316b922254092f217793e8dc129c600c4154471d7a396784468ad24444966bf3R8 ?

2025-01-24 01:16 UTC, jkhusanov commented on src/utils/scaleHelpers.js
> +      (segment.scale !== undefined && _isInvalidScale(segment.scale)) ||
can be a follow-up small PR.

2025-01-24 01:26 UTC, jkhusanov approved these changes
Thank you for all the changes, tested locally looks good!

2025-01-24 13:56 UTC, roni-castro-shipt commented on src/utils/scaleHelpers.js
> +      (segment.scale !== undefined && _isInvalidScale(segment.scale)) ||
I didn’t add those because they’re unexpected values. The library accepts them, shows a warning, and generates a placeholder for missing scale or arcDegree. I haven’t seen this issue in the project, though there are other edge cases, like multiple 1s summing over 1. I felt it was best to focus on app stability, as handling all possible cases seems more like the client’s responsibility than the library’s.

2025-01-24 14:15 UTC, roni-castro-shipt commented on src/components/DataErrorRenderer.js
> +  }
Do you mean avoiding rendering both this component and the default library DataError component?
```js
  if (typeof dataErrorComponent === 'function') {
    throw new Error(
      "'dataErrorComponent' must be a JSX element, not a functional component. Use '<FunctionalComponent />' instead."
    );
  }
```
To not accept this case?
![Screenshot 2025-01-24 at 11 08 19](https://github.com/user-attachments/assets/ea3ff202-ee0c-46ed-a55e-48d1ccde4224)

```js
  it("throws an error if 'dataErrorComponent' is passed as a functional component instead of JSX", () => {
    const FunctionalComponent = () => <Text>Test Functional Component</Text>;
    
    expect(() => 
      render(<DataErrorRenderer dataErrorComponent={FunctionalComponent} />)
    ).toThrow("'dataErrorComponent' must be a JSX element, not a functional component. Use '<FunctionalComponent />' instead.");
  });
```

2025-01-24 19:27 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  }
No, I meant this is uncommon that you would pass functional component.

2025-01-24 19:36 UTC, roni-castro-shipt commented on src/components/DataErrorRenderer.js
> +  }
I agree, as I'm not passing any props to it, but if I don't accept a functional component, the options would be to either render `<DataError />`, `throw an error`, or return null (it seems not appropriate for this case). Should I change to one of these solutions?

2025-01-24 23:21 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  }
If you think this is the common approach, we can keep it as it is and no changes are necessary. I just haven't seen this before.

2025-01-27 18:16 UTC, roni-castro-shipt commented on src/components/DataErrorRenderer.js
> +  }
Updated to allow only types specified in the README (JSX element or null), defaulting to render the DataError component.

2025-01-27 20:19 UTC, jkhusanov requested changes

2025-01-27 20:19 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  throw createInvalidDataErrorComponentError();
We should not throw errors to JSX like this it's going to cause an app crash. Also, I don't think we need this as prop types can provide this check.

2025-01-27 20:19 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  dataErrorComponent: PropTypes.oneOfType([PropTypes.func, PropTypes.elementType]),
Please remove function type, it's not working for valid JSX

2025-01-27 20:19 UTC, jkhusanov commented on src/SegmentedArc.js
> +  dataErrorComponent: PropTypes.oneOfType([PropTypes.func, PropTypes.elementType]),
Same here, after latest changes we don't need func type

2025-01-27 20:28 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  dataErrorComponent: PropTypes.oneOfType([PropTypes.func, PropTypes.elementType]),
If we use `PropTypes.element` this should take care of function being passed

2025-01-27 20:28 UTC, jkhusanov commented on src/SegmentedArc.js
> +  dataErrorComponent: PropTypes.oneOfType([PropTypes.func, PropTypes.elementType]),
same here, if we use PropTypes.element this should take care of function being passed

2025-01-27 20:30 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +import React from 'react';
I think we should just use this simple approach: 

```js
import React from 'react';
import PropTypes from 'prop-types';
import DataError from './DataError';
import { DATA_ERROR_SELECTORS } from '../utils/dataErrorSelectors';
import { SegmentedArcError } from '../utils/segmentedArcErrors';

export const createInvalidDataErrorComponentError = () => {
  return new SegmentedArcError(`'dataErrorComponent' should be a valid JSX element or null.`);
};

const DataErrorRenderer = ({ dataErrorComponent, style }) => {
  if (dataErrorComponent === null) return null;

  if (React.isValidElement(dataErrorComponent)) {
    return dataErrorComponent;
  }

  return <DataError style={style} testID={DATA_ERROR_SELECTORS.CONTAINER} />;
};

DataErrorRenderer.propTypes = {
  dataErrorComponent: PropTypes.element,
  style: PropTypes.object
};

export default DataErrorRenderer;
```

2025-01-27 20:54 UTC, roni-castro-shipt commented on src/components/DataErrorRenderer.js
> +  throw createInvalidDataErrorComponentError();
This approach will remain functional until React 19 is [applied](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis), where PropTypes is no longer checking for anything. However, that's a concern for the future. Additionally, it's worth noting that [PropTypes.elementType](https://github.com/facebook/react/issues/5143) currently treats strings as valid element types. So, to avoid rendering any of that, I'll return null for any value that is neither undefined nor a valid React element, ignoring what is being passed

2025-01-27 21:22 UTC, jkhusanov commented on src/components/DataErrorRenderer.js
> +  throw createInvalidDataErrorComponentError();
thanks, we have plans to revisit PropTypes in the future. As mentioned earlier `element` should cover string.

2025-01-27 21:41 UTC, jkhusanov approved these changes

2025-01-30 17:49 UTC, calebmackdavenport approved these changes

2025-01-30 19:25 UTC, merged