Update CODEOWNERS
shipt/segmented-arc-for-react-native pull request #67
Opened 2024-02-08 21:21 UTC by calebmackdavenport

2024-02-08 21:28 UTC, jkhusanov commented on .github/CODEOWNERS
> +* @jkhusanov @ChiefoftheOwls @marquessv @calebmackdavenport
Could we remove `@ChiefoftheOwls @marquessv` ?

2024-03-15 15:15 UTC, joshuakg approved these changes

2024-03-25 13:23 UTC, TannerDrayton approved these changes

2024-03-25 13:54 UTC, rkyle35242 approved these changes
Do we need more folks than just you two?

2024-03-26 17:25 UTC, rkyle35242 commented on .github/CODEOWNERS
> +* @jkhusanov @calebmackdavenport @rkyle35242
![](https://media1.tenor.com/m/-vpzQN9wafQAAAAC/not-like-this-matrix.gif)

2024-03-26 17:26 UTC, rkyle35242 commented on .github/CODEOWNERS
> +* @jkhusanov @calebmackdavenport @rkyle35242
jk, I'm cool to be on here

2024-04-02 18:39 UTC, rkyle35242 commented
@calebmackdavenport let's just get all the seniors+ on here

2024-04-02 18:39 UTC, rkyle35242 requested changes
Let's just add all the engineers that are Senior and up

2024-04-11 17:37 UTC, jkhusanov approved these changes

2024-04-11 17:38 UTC, merged